// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/block/{userid}": {
            "get": {
                "description": "유저의 블록 보유 확인 후 (없으면 생성 후)리턴",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "유저의 블록 보유 확인 및 생성",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write Block ID",
                        "name": "userid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Block"
                        }
                    }
                }
            }
        },
        "/api/item/collection/{collectionid}": {
            "get": {
                "description": "Collection ID를 넣으면 Collection을 리턴함",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "Collection By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write Block ID",
                        "name": "collectionid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Collection"
                        }
                    }
                }
            }
        },
        "/api/item/group/{groupid}": {
            "get": {
                "description": "Product Group ID를 넣으면 -\u003e Group을 반환함.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "GetProductGroup By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write Block ID",
                        "name": "groupid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ProductGroup"
                        }
                    }
                }
            }
        },
        "/api/item/nft/": {
            "post": {
                "description": "Nft ID를 넣으면 -\u003e NFT를 반환함.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "GetNftById By ID",
                "parameters": [
                    {
                        "type": "string",
                        "name": "group_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "group ID",
                        "name": "groupid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Resp"
                        }
                    }
                }
            }
        },
        "/api/item/nft/{nftid}": {
            "get": {
                "description": "Nft ID를 넣으면 -\u003e NFT를 반환함.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Item"
                ],
                "summary": "GetNftById By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write Block ID",
                        "name": "nftid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Nft"
                        }
                    }
                }
            }
        },
        "/api/obj/airdrop": {
            "post": {
                "description": "Wallet생성도 해주고, NFT 생성 해주고, Obj 생성!",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Obj"
                ],
                "summary": "에어드랍진행 !",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write Block ID",
                        "name": "ReqBody",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Obj"
                        }
                    }
                }
            }
        },
        "/api/obj/msg/paging/{page}/{limit}": {
            "get": {
                "description": "Wallet생성도 해주고, NFT 생성 해주고, Obj 생성!",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Obj"
                ],
                "summary": "에어드랍진행 !",
                "parameters": [
                    {
                        "type": "string",
                        "description": "페이지입력",
                        "name": "page",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "조회갯수제한",
                        "name": "limit",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Obj_msg"
                        }
                    }
                }
            }
        },
        "/api/obj/msg/{id}": {
            "get": {
                "description": "Obj Msg 단일 조회 기능 (단일, ID값 기준)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Obj"
                ],
                "summary": "Obj Msg 단일 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write ObjMSG ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Obj_msg"
                        }
                    }
                }
            }
        },
        "/api/obj/{blockid}": {
            "get": {
                "description": "블록아이디를 넣으면 오브제를 리턴함.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Obj"
                ],
                "summary": "블록아이디로 오브제를 가져오는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Write Block ID",
                        "name": "blockid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Obj"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Resp": {
            "type": "object",
            "properties": {
                "nft": {
                    "$ref": "#/definitions/model.Nft"
                },
                "tx": {
                    "$ref": "#/definitions/model.NftTx"
                }
            }
        },
        "model.Block": {
            "type": "object",
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "thema": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Collection": {
            "type": "object",
            "required": [
                "name_en",
                "name_ko",
                "publisher_en",
                "publisher_ko"
            ],
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "discord_url": {
                    "type": "string"
                },
                "id": {
                    "description": "PK",
                    "type": "integer"
                },
                "name_en": {
                    "type": "string"
                },
                "name_ko": {
                    "type": "string"
                },
                "opensea_url": {
                    "type": "string"
                },
                "publisher_en": {
                    "type": "string"
                },
                "publisher_ko": {
                    "type": "string"
                },
                "twitter_url": {
                    "type": "string"
                },
                "ww_url": {
                    "type": "string"
                }
            }
        },
        "model.Nft": {
            "type": "object",
            "required": [
                "description",
                "name_en",
                "name_ko",
                "product_id",
                "token_id"
            ],
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name_en": {
                    "type": "string"
                },
                "name_ko": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "properties": {
                    "type": "string"
                },
                "token_id": {
                    "type": "integer"
                },
                "updated_time": {
                    "type": "string"
                }
            }
        },
        "model.NftTx": {
            "type": "object",
            "required": [
                "from",
                "method",
                "nft_id",
                "to"
            ],
            "properties": {
                "created_time": {
                    "type": "string"
                },
                "from": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "integer"
                },
                "nft_id": {
                    "type": "integer"
                },
                "to": {
                    "type": "integer"
                }
            }
        },
        "model.Obj": {
            "type": "object",
            "required": [
                "block_id",
                "pos",
                "rot",
                "user_id"
            ],
            "properties": {
                "block_id": {
                    "type": "integer"
                },
                "building_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "description": "PK",
                    "type": "integer"
                },
                "nft_id": {
                    "type": "integer"
                },
                "pos": {
                    "type": "string"
                },
                "rot": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_user": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Obj_msg": {
            "type": "object",
            "required": [
                "created_user",
                "message",
                "obj_id",
                "type",
                "updated_user"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_user": {
                    "type": "integer"
                },
                "id": {
                    "description": "PK",
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "obj_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_user": {
                    "type": "integer"
                }
            }
        },
        "model.ProductGroup": {
            "type": "object",
            "required": [
                "collection_id",
                "contract"
            ],
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "collection_id": {
                    "type": "integer"
                },
                "contract": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "message_amount": {
                    "type": "integer"
                },
                "message_role": {
                    "description": "MSG Role을 여기서 주어야 하는가..에 대한 의문.",
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "name_en": {
                    "type": "string"
                },
                "name_ko": {
                    "type": "string"
                },
                "properties": {
                    "type": "string"
                },
                "snap": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "updated_time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
